repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: mypy
      name: mypy

      entry: mypy
      language: system
      # run if any Python file is changed
      types: [python]
      # mypy will always check all files
      pass_filenames: true
      # use require_serial so that script is only called once per commit
      require_serial: true

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
