[mypy]
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main
mypy_path = backend
explicit_package_bases = True
python_version = 3.11
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = server.settings
strict_settings = false
ignore_missing_settings = true
ignore_missing_model_attributes = true

[mypy-apps.*]
ignore_missing_imports = True

[mypy-apps.budget.views]
ignore_errors = True

[mypy-*.migrations.*]
ignore_errors = True

[mypy-frontend.*]
ignore_missing_imports = True
