# Generated by Django 4.2.4 on 2023-12-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_alter_statement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="category",
            field=models.CharField(max_length=400),
        ),
    ]
