# Generated by Django 4.2.4 on 2024-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="card",
            field=models.CharField(default="Unknown", max_length=30),
        ),
    ]
