# Generated by Django 4.2.4 on 2026-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_statement_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("columns", models.JSONField(default=dict)),
                ("amount_sign", models.CharField(default="as_is", max_length=20)),
                ("dayfirst", models.BooleanField(default=True)),
                (
                    "default_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "default_card",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "header_signature",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
